const question = {
    dirty: [
        'Never have I ever kiss and told.',
        'Never have I ever been on a blind date.',
        'Never have I ever had a date with someone I met on an app.',
        'Never have I ever made out with a stranger.',
        'Never have I ever tried a cheesy pick-up line on someone.',
        'Never have I ever had a cheesy pick-up line work on me.',
        'Never have I ever sent someone a sexy selfie.',
        'Never have I ever been on a double date with my parents.',
        'Never have I ever tried skinny dipping.',
        'Never have I ever gone commando.',
        'Never have I ever made out with someone in a hot tub.',
        'Never have I ever had a one night stand.',
        "Never have I ever had a crush on a friend's sibling.",
        'Never have I ever flirted with someone more than 10 years older than me.',
        'Never have I ever been to a drive-in movie.',
        'Never have I ever been a friend with benefits.',
        'Never have I ever skipped a movie to make out in the parking lot instead.',
        'Never have I ever been playful with whipped cream.',
        'Never have I ever winked or whistled at someone.',
        'Never have I ever slept in the buff.',
        'Never have I ever looked at naughty pictures.',
        'Never have I ever dated more than one person at once.',
        'Never have I ever seen someone else naked in person.',
        'Never have I ever bought lingerie.',
        'Never have I ever been to an adult store.',
        'Never have I ever watched a movie because I knew it had nudity.',
        'Never have I ever played strip poker.',
        'Never have I ever done it in a public place.',
        'Never have I ever passed second base.',
        'Never have I ever peeked at someone in the shower.',
        'Never have I ever had a dream about someone I liked.',
        'Never have I ever had a crush on a teacher.',
        'Never have I ever slipped someone my phone number.',
        "Never have I ever gently whispered in someone's ear.",
        'Never have I ever played hard to get.',
        'Never have I ever had a hickey.',
        'Never have I ever given someone else a hickey.',
        'Never have I ever stayed friends with an ex.',
        'Never have I ever done it outside.',
        'Never have I ever had a bedroom injury.',
        'Never have I ever had breakfast in bed.',
        'Never have I ever had a full-body massage.',
        "Never have I ever adjusted my buttons based on who's in the room.",
        'Never have I ever fantasized about someone else.',
        'Never have I ever made any naughty videos.',
        'Never have I ever had sex in a public place.',
        'Never have I ever sent a dirty text to the wrong person.',
        'Never have I ever said the wrong name in bed.',
        'Never have I ever had a friend with benefits.',
        "Never have I ever slept with someone whose name I don't know.",
        'Never have I ever been to an adult store.',
        'Never have I ever had a threesome.',
        "Never have I ever joined the 'mile high' club.",
        'Never have I ever sent a sexy selfie.',
        'Never have I ever had sex in the sea/a swimming pool.',
        'Never have I ever had a one night stand.',
        'Never have I ever faked an orgasm.',
        'Never have I ever flashed someone.',
        'Never have I ever given or received a lap dance.',
        "Never have I ever been 'walked in on' while having sex.",
    ],
    tipsy: [
        'Never have I ever been drunk at a restaurant.',
        'Never have I ever played beer pong.',
        'Never have I ever tried to do a keg stand.',
        'Never have I ever drank before I turned 21.',
        'Never have I ever partied during spring break.',
        'Never have I ever tried Champagne.',
        'Never have I ever said a toast.',
        'Never have I ever drank more than 3 beers in a sitting.',
        'Never have I ever drank alcohol in front of my parents.',
        'Never have I ever fallen asleep and woken up somewhere else.',
        'Never have I ever danced on a table or bar.',
        'Never have I ever pretended to like a wine to look classier.',
        'Never have I ever drank liquor straight from the bottle.',
        'Never have I ever received a free drink.',
        "Never have I ever texted someone I didn't mean to when I was tipsy.",
        'Never have I ever left a drunk voicemail.',
        'Never have I ever been the designated driver.',
        'Never have I ever tried a craft beer.',
        'Never have I ever toured a brewery.',
        'Never have I ever tried moonshine.',
        'Never have I ever watched the Hangover.',
        'Never have I ever been hungover.',
        'Never have I ever tried wine in a box.',
        'Never have I ever purchased alcohol duty-free on a cruise.',
        'Never have I ever broke up with someone while drunk.',
        'Never have I ever found a cure for hangovers.',
        'Never have I ever made up my own cocktail.',
        'Never have I ever had a jello shot.',
        'Never have I ever made vodka gummy bears.',
        'Never have I ever been to a wine tasting.',
        'Never have I ever drank Crown Royal.',
        'Never have I ever made an impulse purchase online while drunk.',
        "Never have I ever drunkenly posted something on Facebook that I wished I hadn't.",
        'Never have I ever lost count of how many drinks I drank.',
        'Never have I ever had to be carried to bed.',
        "Never have I ever played 'Never have I ever' before.",
        'Never have I ever been the drunkest person at the party.',
        'Never have I ever drank at a bar.',
        'Never have I ever taken a shot with no hands.',
        'Never have I ever had a stranger buy me a drink.',
        'Never have I ever shotgunned a beer.',
        'Never have I ever done a pub-crawl.',
        'Never have I ever drank a flaming shot.',
        'Never have I ever done a body shot.',
        'Never have I ever participated in a drinking competition.',
    ],
    embarrassing: [
        'Never have I ever farted in front of someone I liked.',
        'Never have I ever accidentally sharted.',
        'Never have I ever forgotten the punchline of a joke.',
        'Never have I ever sang a song out loud and messed the lyrics.',
        'Never have I ever walked in on someone in the bathroom.',
        'Never have I ever had someone walk in on me in the bathroom.',
        'Never have I ever sent a text to the wrong person.',
        'Never have I ever tried to pass a silent fart, but it came out loud instead.',
        'Never have I ever tripped in public.',
        'Never have I ever wet the bed after childhood.',
        'Never have I ever accidentally pooped my pants.',
        'Never have I ever attempted martial arts moves while by myself.',
        'Never have I ever drove over a curb.',
        'Never have I ever mistaken a man for a women or vice versa.',
        'Never have I ever laughed so hard, I peed my pants.',
        'Never have I ever picked a wedgie in public.',
        'Never have I ever called the wrong person, but pretended I meant to call them.',
        'Never have I ever gone into the wrong restroom.',
        'Never have I ever been so freaked to be outside at night, that I ran back in.',
        'Never have I ever lost my swimwear bottoms.',
        "Never have I ever had diarrhea at a friend's house.",
        'Never have I ever broken a piece of furniture by sitting on it.',
        'Never have I ever arrived somewhere late and had everyone staring at me.',
        'Never have I ever had food stuck in my teeth all day.',
        'Never have I ever walked around with my zipper down.',
        "Never have I ever bought a children's toy for myself, as an adult.",
        'Never have I ever recorded video of myself singing or dancing.',
        'Never have I ever been caught picking my nose.',
        'Never have I ever gotten something stuck in my nose.',
        'Never have I ever greeted someone I thought was someone else.',
        'Never have I ever gave myself a bad haircut.',
        'Never have I ever been told I had bad breath.',
        'Never have I ever screamed because of a bug.',
        "Never have I ever played on my phone, trying to look like I'm doing something important.",
        'Never have I ever practiced public speaking in the mirror.',
        'Never have I ever had dandruff.',
        'Never have I ever listened to Justin Bieber.',
        'Never have I ever just looked at myself naked in the mirror.',
        'Never have I ever pretended to wash my hands by turning the water on, just in case someone is listening.',
        "Never have I ever smiled at someone when I realize I wasn't listening to what they were saying.",
        'Never have I ever tried to impress a crush by seeming knowledgeable about things they liked.',
        'Never have I ever refreshed over and over to see if I have any new messages.',
        'Never have I ever pretended to text while you secretly take a million selfies.',
        'Never have I ever been obsessed with One Direction.',
        'Never have I ever imagined my life as a sitcom and who would play me.',
    ],
};

export default question;
